use empresaclase;

/*
EN ESTE EJEMPLO LO QUE QUIERO ES QUE ME MUESTRE TODOS LOS VALORES DE LA TABLA DE EMPLEADOS
COMO DE LA TABLA DE DEPARTAMENTOS, PARA ELLO HAGO USO DEL 'INNER JOIN'. 
EL INER JOIN SE USA PARA UNIR TABLAS.
LA CLÁUSULA INNER JOIN SELECCIONA SOLO LOS REGISTRTOS QUE TIENEN VALORES COINCIDENTES EN AMBAS TABLAS. .
*/
select * 
	from empleados
		inner join departamentos on empleados.numde = departamentos.numde;
        -- join departamentos on empleados.numde = departamentos.numde; -- CON O SIN EN INNER SE MUESTRA LO MISMO.
        
/*
 A DIFERENCIA DEL INNER JOIN EL LEFT JOIN LO QUE HACE ES INCLUIR TODOS AQUELLOS VALORES QUE AUNQ NO CUNPLAN CON 
 LAS DOS CONDICIONES QUE LES ESTAMOS DICIENDO, SEAN MOSTRADAS EN LA NUEVA TABLA QUE SLAGA POR CONSOLA Y QUE ADEMAS
 SI LA CONDICION NO SE CUMPLE SE MUESTRE ESE CAMPO DE LA TABLA QUE HEMOS MARCADO COMO CONDICION PERO QUE SE PONGA NULL
*/        
select * 
	from empleados
		inner join departamentos on empleados.numde = departamentos.numde; 
-- AQUI ESTANIS DICIENDO QUE SI HAY UN EMPLEADO QUE NO TIENE DEPARTAMENTO QUE NOS MUESTRE LOS DATOS DE DICHO EMPLEADO
-- DENTRO DE LA TABLA EMPLEADOS PERO QUE AQUELLOS DATOS DEL EMPLEADO QUE DEBERÍAN DE SALIR EN DEPARTAMENTOS SEAN NULL. 
-- LA CONDICION DE LA QUE HABLO ES LA DE LA UNION ENTRE AMBAS TABLAS QUE EN ESTE CASO ES 'numde'.